@startuml

left to right direction
:Cliente:
:Cliente: -- (Meter dinero)
:Cliente: -- (Pedir azucar)
:Cliente: -- (Pedir Producto)
:Cliente: -- (Cancelar)
(Pedir Producto) ..>(Devolver dinero) : <<include>>
(Cancelar) ..> (Devolver dinero) : <<include>>

@enduml